import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Check, Clock } from "lucide-react";
import { PUBLIC_MODELS } from "@/lib/catalog/public-models";
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return PUBLIC_MODELS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const m = PUBLIC_MODELS.find((x) => x.slug === slug); return m ? { title: `${m.nome} | DocFácil`, description: m.descricao, alternates: { canonical: `/documentos/${slug}` } } : {}; }
export default async function Page({ params }: Props) { const { slug } = await params; const m = PUBLIC_MODELS.find((x) => x.slug === slug); if (!m) notFound(); return <article className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:py-20"><Link href="/documentos" className="inline-flex min-h-11 items-center gap-2 font-semibold text-blue-900"><ArrowLeft className="size-4" /> Todos os documentos</Link><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div className="flex flex-wrap gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-900">{m.categoria}</span><span className="flex items-center gap-1 text-sm text-slate-600"><Clock className="size-4" /> Cerca de {m.minutos} min</span></div><h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl">{m.nome}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{m.descricao}</p><h2 className="mt-9 text-2xl font-bold">Quando usar</h2><p className="mt-3 leading-7 text-slate-700">{m.quandoUsar}</p><ul className="mt-8 grid gap-3 text-slate-700 sm:grid-cols-2">{["Perguntas em linguagem simples", "Prévia antes de gerar o PDF", "Documento com acabamento profissional", "Uso confortável pelo celular"].map((x) => <li key={x} className="flex gap-2"><Check className="mt-1 size-5 text-emerald-700" />{x}</li>)}</ul><p className="mt-8 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">O DocFácil ajuda a montar o documento, mas não substitui orientação jurídica para situações complexas nem serviços de cartório quando forem exigidos.</p><Link href={`/?view=criar&slug=${m.slug}`} className="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-blue-900 px-6 font-bold text-white sm:w-auto">Começar este documento</Link></div></article>; }
