"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Search, Clock, ArrowRight } from "lucide-react";
import type { PublicModel } from "@/lib/catalog/search";
import { searchPublicModels } from "@/lib/catalog/search";
export function DocumentCatalog({ models }: { models: PublicModel[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("Todos");
  const categories = ["Todos", ...new Set(models.map((m) => m.categoria))];
  const results = useMemo(() => searchPublicModels(models, query).filter((m) => category === "Todos" || m.categoria === category), [models, query, category]);
  return <div><label className="relative block max-w-2xl"><span className="sr-only">Buscar um documento</span><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-slate-500" aria-hidden="true" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Ex.: aluguel, procuração ou declaração" className="h-14 w-full rounded-2xl border border-slate-300 bg-white pl-12 pr-4 text-base shadow-sm outline-none focus:border-blue-700 focus:ring-4 focus:ring-blue-100" /></label><div className="my-5 flex gap-2 overflow-x-auto pb-2" aria-label="Filtrar por categoria">{categories.map((item) => <button key={item} type="button" aria-pressed={category === item} onClick={() => setCategory(item)} className={`min-h-11 shrink-0 rounded-full px-4 text-sm font-semibold ${category === item ? "bg-blue-900 text-white" : "border border-slate-300 bg-white text-slate-700"}`}>{item}</button>)}</div><p className="mb-5 text-sm text-slate-600" aria-live="polite">{results.length} {results.length === 1 ? "documento encontrado" : "documentos encontrados"}</p>{results.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.map((m) => <article key={m.slug} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-900">{m.categoria}</span>{m.free && <span className="text-xs font-semibold text-emerald-700">Opção gratuita</span>}</div><h2 className="text-xl font-bold text-slate-950">{m.nome}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{m.descricao}</p><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Clock className="size-4" /> Cerca de {m.minutos} min</p><Link href={`/documentos/${m.slug}`} className="mt-5 inline-flex min-h-11 items-center justify-between rounded-xl bg-slate-100 px-4 font-semibold text-blue-950">Ver detalhes <ArrowRight className="size-4" /></Link></article>)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><p className="font-semibold">Não encontramos esse documento.</p><button className="mt-3 min-h-11 text-blue-800 underline" onClick={() => { setQuery(""); setCategory("Todos"); }}>Limpar filtros</button></div>}</div>;
}
